service: personal-finance-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createTransaction:
    handler: src/interface/lambda/createTransaction.handler
    events:
      - http:
          path: transactions
          method: post
          cors: true

  getTransactions:
    handler: src/interface/lambda/getTransactions.handler
    events:
      - http:
          path: transactions
          method: get
          cors: true

  getTransactionById:
    handler: src/interface/lambda/getTransactionById.handler
    events:
      - http:
          path: transactions/{id}
          method: get
          cors: true

  updateTransaction:
    handler: src/interface/lambda/updateTransaction.handler
    events:
      - http:
          path: transactions/{id}
          method: put
          cors: true

  deleteTransaction:
    handler: src/interface/lambda/deleteTransaction.handler
    events:
      - http:
          path: transactions/{id}
          method: delete
          cors: true


  getReports:
      handler: src/interface/lambda/getReports.handler
      events:
        - http:
            path: reports
            method: get
            cors: true

  getCategories:
    handler: src/interface/lambda/getCategories.handler
    events:
      - http:
          path: categories
          method: get
          cors: true

custom:
  serverless-offline:
    httpPort: 3001
  dotenv:
    path: .env    